vocabulary/authentication/urls.py
from django.urls.conf import path
from authentication.apiviews import UserRegistrationAPIView, UsernameAPIView, UserAPIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from authentication.views import SignupView, LoginView
from django.contrib.auth import views as auth_views


app_name = 'authentication'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='sign-up'),
    path('login/', LoginView.as_view(), name='login'),
    
    # path('login/', auth_views.LoginView.as_view(template_name="authentication/login.html"), name='login'),

    # REST urls
    path('api/signup/', UserRegistrationAPIView.as_view(), name='api-signup'),
    path('api/fetch-username/', UsernameAPIView.as_view(), name='api-fetch-username'),
    path('api/fetch-user/', UserAPIView.as_view(), name='api-fetch-user'),

    # JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

vocabulary/vocabulary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import *
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='manage-vocabulary/vocabulary-list/', permanent=False)),
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view(), name='index'),

    # Registered app urls
    path('auth/', include('authentication.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('manage-vocabulary/', include('manage_vocabulary.urls', namespace='manage-vocabulary')),
]

vocabulary/authentication/models.py
from django.db import models

# Create your models here.

vocabulary/authentication/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.
class SignupView(TemplateView):
    template_name = 'authentication/signup.html'


class LoginView(TemplateView):
    template_name = 'authentication/login.html'

vocabulary/authentication/templates/authentication/authenticate.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brian's Dictionary | Authenticate</title>

    <link rel="stylesheet" href="{% static 'vendors/bootstrap-5.0.2/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/boxicons-2.1.1/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'customs/authentication/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'customs/css/buttons.css' %}">
</head>
<body>
    <div class="sign-up-form-container">
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-6 col-xs-6 justify-content-center sign-up-form-box">
            <h5 class="text-center">Brian's Dictionary</h5>
            <div class="" id="login-alert" role="alert"></div>
            <div class="login-form">
               <div class="row justify-content-center">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <button id="sign-up-btn" class="btn btn-sm auth-btn" style="width: 100%;">SIGNUP</button>
                    </div>
               </div>
               <br>
               <div class="row justify-content-center">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <button id="login-btn" class="btn btn-sm auth-btn mb-2" style="width: 100%;">Login</button>
                </div>
           </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
    </div>
    <div class="loading-spinner-overlay" id="loading-spinner" style="display: none;">
        <div class="loading-spinner">
            <div class="spinner-grow text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
      </svg>
</body>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'vendors/jquery-3.5.1/dist/jquery.js' %}"></script>
<!-- Popper -->
<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'customs/authentication/js/master.js' %}"></script>
<script>
    $(document).ready(function() {
        $LOGIN_ALERT.hide();
    })
    var BASE_URL = "https://addwordstoenglish.com/";
    
    var $LOGIN_BTN = $("#login-btn");
    var $SIGN_UP_BTN = $("#sign-up-btn");
    var $LOGIN_ALERT = $("#login-alert");
    var $SPINNER = $("#loading-spinner");
    
    $SIGN_UP_BTN.click(function () {
        window.location.replace(BASE_URL + 'auth/signup/');
    })

    $LOGIN_BTN.click(function () {
        window.location.replace(BASE_URL + 'auth/login/');
    })
</script>
</html>

vocabulary/authentication/templates/authentication/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brian's Dictionary | Login</title>

    <link rel="stylesheet" href="{% static 'vendors/bootstrap-5.0.2/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/boxicons-2.1.1/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'customs/authentication/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'customs/css/buttons.css' %}">
</head>
<body>
    <div class="sign-up-form-container">
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-6 col-xs-6 justify-content-center sign-up-form-box">
            <h5 class="text-center">Brian's Dictionary</h5>
            <div class="" id="login-alert" role="alert"></div>
            <div class="login-form">
                
                    <div class="row mb-2 justify-content-center">
                        <input id="username" class="form-control form-control-sm" type="text" placeholder="Username" required>
                        <div id="username-validation" class="invalid-feedback"></div>
                    </div>
                    <div class="row mb-3">
                        <input id="password" class="form-control form-control-sm" type="password" placeholder="Password" required>
                        <span class="justify-content-end"><i id="password-hide-icon" class="far fa-eye-slash" onclick="showHidePassword('#password', 'password')"></i></span>
                        <span class="justify-content-end"><i id="password-show-icon" class="far fa-eye"  onclick="showHidePassword('#password', 'password')" style="display: none;"></i></span>
                    </div>
                    <div class="row">
                        <p class="ps-0 ms-0">Forgot password? <a href="#">Reset Password</a></p>
                    </div>

                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="row mb-2">
                        <Button id="login-btn" class="btn btn-sm auth-btn">LOGIN</Button>
                    </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
    </div>
    <div class="loading-spinner-overlay" id="loading-spinner" style="display: none;">
        <div class="loading-spinner">
            <div class="spinner-grow text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
      </svg>
</body>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'vendors/jquery-3.5.1/dist/jquery.js' %}"></script>
<!-- Popper -->
<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'customs/authentication/js/master.js' %}"></script>
<script>
    $(document).ready(function() {
        $LOGIN_ALERT.hide();
    })
    var BASE_URL = "https://addwordstoenglish.com/";
    
    var $USERNAME = $("#username");
    var $PASSWORD = $("#password");
    var $LOGIN_BTN = $("#login-btn");
    var $LOGIN_ALERT = $("#login-alert");
    var $SPINNER = $("#loading-spinner");

    // $PASSWORD.keyup(function (event) {
    //     if (event.keyCode === 13) {
    //         $LOGIN_BTN.click();
    //     }        
    // })

    $LOGIN_BTN.click(function () {
        $SPINNER.show();
        var username = $("#username").val();
        var password = $("#password").val();
        $.ajax({
            type: 'GET',
            url: '{% url "authentication:api-fetch-username" %}',
            data: {
                'username': username,
            },
            success: function (data) {
                console.log('# ---- Fetch username success ---- #');
                if (data.username) {
                    var fetched_username = data.username;

                    $.ajax({
                        type: 'POST',
                        url: '{% url "authentication:token_obtain_pair" %}',
                        headers: {
                            "Content-Type": "application/x-www-form-urlencoded"
                        },
                        data: {
                            'username': fetched_username,
                            'password': password
                        },
                        success: function (data) {
                            $SPINNER.hide();
                            console.log('# ---- Authorization success ---- #');
                            if (data.access) {
                                if (!localStorage.getItem('access')) {
                                    localStorage.setItem('access', data.access);
                                } else {
                                    localStorage.removeItem('access');
                                    localStorage.setItem('access', data.access);
                                }
                            }

                            if (data.refresh) {
                                if (!localStorage.getItem('refresh')) {
                                    localStorage.setItem('refresh', data.refresh);
                                } else {
                                    localStorage.removeItem('refresh');
                                    localStorage.setItem('refresh', data.refresh);
                                }
                            }
                            window.location.replace(BASE_URL + 'manage-vocabulary/vocabulary-list/');
                        },
                        error: function (error) {
                            console.log('# ---- Authorization error ---- #');
                            $SPINNER.hide();
                            if (error.status == 401) {
                                $LOGIN_ALERT.addClass("alert alert-danger");
                                $LOGIN_ALERT.append('<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>');
                                $LOGIN_ALERT.append(`<span>Username or password does not match.</span>`);
                                $LOGIN_ALERT.show(); 
                            }
                        }
                    })
                }                
            },
            error: function (error) {
                console.log('# ---- Fetch username error ---- #');
            }
        })
    })

    
</script>
</html>

vocabulary/authentication/templates/authentication/signup.html
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brian's Dictionary | Sign Up</title>

    <link rel="stylesheet" href="{% static 'vendors/bootstrap-5.0.2/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/boxicons-2.1.1/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome-6.0.0/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'customs/authentication/css/master.css'%}">
    <link rel="stylesheet" href="{% static 'customs/css/buttons.css' %}">
</head>
<body>
    <div class="sign-up-form-container">
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-4 col-xs-4 justify-content-center sign-up-form-box">
            <h5 id="head" class="text-center">Brian's Dictionary</h5>
            <div class="" id="sign-up-alert" role="alert">
            </div>
            <div class="sign-up-form">
                <div class="row mb-2 justify-content-center">
                    <input id="username" class="form-control form-control-sm" type="text" placeholder="Username" value="">
                    <div id="username-validation" class="invalid-feedback"></div>
                </div>
                <div class="row mb-2 justify-content-center">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="row me-0">
                            <input id="first-name" class="form-control form-control-sm" type="text" placeholder="First Name">
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="row ms-0">
                            <input id="last-name" class="form-control form-control-sm" type="text" placeholder="Last Name">
                        </div>
                    </div>
                </div>
                <div class="row mb-2">
                    <input id="email" class="form-control form-control-sm" type="text" placeholder="Email">
                    <div id="email-validation" class="invalid-feedback"></div>
                </div>
                <div class="row mb-2">
                    <input id="password" class="form-control form-control-sm" type="password" placeholder="Password">
                    <span class="justify-content-end"><i id="password-hide-icon" class="far fa-eye-slash" onclick="showHidePassword('#password', 'password')"></i></span>
                    <span class="justify-content-end"><i id="password-show-icon" class="far fa-eye"  onclick="showHidePassword('#password', 'password')" style="display: none;"></i></span>
                    <div id="password-validation" class="invalid-feedback"></div>
                </div>
                <div class="row mb-2">
                    <input id="confirm-password" class="form-control form-control-sm" type="password" placeholder="Confirm Password">
                    <span class="justify-content-end"><i id="confirm-password-hide-icon" class="far fa-eye-slash" onclick="showHidePassword('#confirm-password', 'confirm')"></i></span>
                    <span class="justify-content-end"><i id="confirm-password-show-icon" class="far fa-eye" onclick="showHidePassword('#confirm-password', 'confirm')" style="display: none;"></i></span>
                    <!-- <div id="validationServerUsernameFeedback" class="invalid-feedback">
                        Please choose a username.
                    </div> -->
                </div>
                <div class="row mb-2">
                    <Button type="" id="sign-up-btn" class="btn btn-sm auth-btn">SIGNUP</Button>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
    </div>
    <div class="loading-spinner-overlay" id="loading-spinner" style="display: none;">
        <div class="loading-spinner">
            <div class="spinner-grow text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
      </svg>
</body>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'vendors/jquery-3.5.1/dist/jquery.js' %}"></script>
<!-- Popper -->
<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'customs/authentication/js/master.js' %}"></script>
<script>
    $(document).ready(function() {
        $SIGN_UP_ALERT.hide();
    })

    var $SIGN_UP_BTN = $("#sign-up-btn");
    var $SIGN_UP_ALERT = $("#sign-up-alert");
    var $USERNAME = $("#username");
    var $EMAIL = $("#email");
    var $PASSWORD = $("#password");
    var $SPINNER = $("#loading-spinner");
    var $CONFIRM_PASSWORD = $("#confirm-password");

    var BASE_URL = "https://addwordstoenglish.com/";

    $CONFIRM_PASSWORD.keyup(function (event) {
        if (event.keyCode === 13) {
            $SIGN_UP_BTN.click();
        }
    })

    $SIGN_UP_BTN.click(function() {
        
        $SPINNER.show();
        var username = $("#username").val();
        var firstName = $("#first-name").val();
        var lastName = $("#last-name").val();
        var email = $("#email").val()
        var password = $("#password").val();
        var confirmPassword = $("#confirm-password").val();
    
        if (password === confirmPassword) {
            $.ajax({
                type: 'POST',
                url: '{% url "authentication:api-signup" %}',
                data: {
                    'username': username,
                    'first_name': firstName,
                    'last_name': lastName,
                    'email': email,
                    'password': password
                },
                dataType: 'json',
                success: function (data, status) {
                    console.log('# ---- User signup success ---- #');
                    $SPINNER.hide();
                    window.location.replace(BASE_URL + 'auth/login/');
                },
                error: function (error) {
                    $SPINNER.hide();
                    console.log('# ---- User signup error ----#', error.status);
                    if (error.status == 500) {
                        $PASSWORD.addClass('is-invalid');
                        $("#password-validation").append('This password is too short. It must contain at least 10 characters.');
                    }

                    if (error.status == 400) {
                        if (error.responseJSON.username) {
                            $USERNAME.addClass('is-invalid');
                            $("#username-validation").append(error.responseJSON.username);
                        }

                        if (error.responseJSON.email) {
                            $EMAIL.addClass('is-invalid');
                            $("#email-validation").append('A user with this email address already exists.');
                        }

                        if (error.responseJSON.password) {
                            $PASSWORD.addClass('is-invalid');
                            $("#password-validation").append(error.responseJSON.password);
                        }
                    }
                }
            })
        } else {
            $SPINNER.hide();
            $SIGN_UP_ALERT.addClass("alert alert-danger");
            $SIGN_UP_ALERT.append('<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>');
            $SIGN_UP_ALERT.append(`<span>Password do not match.</span>`);
            $SIGN_UP_ALERT.show();
        }
    })
</script>
</html>